const categories = [{category: "Véhicules", 
                    subcategories: ["Véhicules", "Voitures & Utilitaires", "Motos & Scooters", "Camions & Bus", "Véhicules à Louer", "Equipements & Accessoires"]
                }, 
                {category: "Électronique", 
                subcategories: ["Accessoires téléphone et tablette", "Téléphones & Tablettes","Ordinateurs", "Accessoires informatiques", "Consoles & Jeux vidéos", "Télévisions & Ecrans", "Son & Hi-fi", "Appareils photos et Caméras", "Autres électronique"]
                },
                {category: "Mode", 
                subcategories: ["Mode", "Accessoires coiffures", "Tissus", "Vêtements homme", "Vêtements femme", "Chaussures homme", "Chaussures femme", "Accessoires, montres et bijoux", "Santé, cosmétique et parfums", "Maroquinerie et bagagerie", "Autres accessoires"]
                },
                {category: "Immobilier", 
                subcategories: ["Immobilier", "Villas", "Appartements", "Immeubles", "Terrains", "Bureaux & Commerces"]
                },
                {category: "Electroménager", 
                subcategories: ["Electroménager", "Réfrigérateurs & Congélateurs", "Machine à laver & Laves vaisselles", "Climatisateurs & Ventilateurs", "Cuisinières, Gazinières & Fours", "Autres électoménager"
                ]},
                {category: "Interieur", 
                subcategories: ["Pour la maison", "Meubles, Déco & Jardin", "Vaisselle", "Décoration & Linges de maison", "Jardinage", "Bricolage", "Autres pour la maison"]
                },
                {category: "Emplois", 
                subcategories: ["Emploi", "Offres d'emploi", "Demandes d'emploi"]
                }, 
                {category: "Services", 
                subcategories: ["Services", "Covoiturage", "Cours particuliers", "Babysitting & Nounou", "Ménage & cuisine", "Course, Litrueson & Déménagement", "Travaux, Jardinage & Bricolage", "Prestation de services web, Design & Photo", "Prestations de services Mode, Beauté et Bien-être", "Autres services"]
                },
                {category: "Enfants", 
                subcategories: ["Pour l’enfant", "Vêtements enfants", "Chaussures enfants", "Mobilier & Equipement bébé", "Jeux & Jouets", "Fournitures Scolaires", "Autres pour l'enfant"]
                },
                {category: "Loisirs", 
                subcategories: ["Loisirs", "DVD, CD & Livres", "Vélos", "Instruments de musique", "Sports", "Evènements", "Autres Sports & Loisirs"]
                },
                {category: "Alimentation", subcategories: ["Alimentation"]
                },
                {category: "Animaux", 
                subcategories: ["Animaux","Alimentation","Achat & Vente d'animaux","Matériel pour animaux"]
                },
                {category: "Matériel Pro", 
                subcategories: ["Matériel Pro", "Matériel agricole", "Transport - Manutention", "BTP - Chantier- Gros Oeuvre - Outillage", "Fournitures de bureaux", "Matériel pour Commerces & Marchés", "Matériel médical", "Autre Matériel Professionnel"]}
            ];
const towns = [
'Bali',
'Penja',
'Évodoula',
'Bekondo',
'Okola',
'Poli',
'Somié',
'Edéa',
'Bandjoun',
'Melong',
'Mbanga',
'Kumba',
'Jakiri',
'Fundong',
'Fontem',
'Bertoua',
'Ambam',
'Sangmélima',
'Manjo',
'Lagdo',
'Dschang',
'Ngoro',
'Ndikiniméki',
'Mbalmayo',
'Makary',
'Dizangué',
'Bogo',
'Njinikom',
'Bonabéri',
'Tcholliré',
'Nanga Eboko',
'Mamfe',
'Limbe',
'Kribi',
'Koza',
'Garoua',
'Belo',
'Akom II',
'Yokadouma',
'Kaélé',
'Eséka',
'Bana',
'Yagoua',
'Rey Bouba',
'Mbandjok',
'Foumban',
'Bétaré Oya',
'Yoko',
'Ndelele',
'Abong Mbang',
'Mora',
'Akono',
'Tiko',
'Mutengene',
'Mindif',
'Essé',
'Dibombari',
'Banyo',
'Yabassi',
'Tibati',
'Bankim',
'Bélabo',
'Bafia',
'Nkongsamba',
'Kousséri',
'Bazou',
'Saa',
'Lolodorf',
'Garoua Boulaï',
'Bansoa',
'Ngomedzap',
'Ngambé',
'Mundemba',
'Mbankomo',
'Mbang',
'Loum',
'Guider',
'Douala',
'Djohong',
'Bangangté',
'Yaoundé',
'Tignère',
'Mouanko',
'Mbouda',
'Mbengwi',
'Buea',
'Bafoussam',
'Ndom',
'Ngaoundéré',
'Bélel',
'Nkoteng',
'Mokolo',
'Foumbot',
'Bamendjou',
'Bamenda',
'Akonolinga',
'Ombésa',
'Okoa',
'Kumbo',
'Batibo',
'Ngou',
'Bamusso',
'Babanki',
'Kontcha',
'Dimako',
'Bafang',
'Pitoa',
'Nguti',
'Meïganga',
'Diang',
'Mme-Bafumen',
'Ébolowa',
'Doumé',
'Wum',
'Tonga',
'Obala',
'Ntui',
'Mvangué',
'Minta',
'Maroua',
'Batouri'
];

export {towns, categories};